services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-housing}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-housing}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - housing-network

  dagster-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run dagster-daemon run -w /opt/dagster/dagster_home/workspace.yaml
    environment:
      PYTHONPATH: /app
      DAGSTER_HOME: /opt/dagster/dagster_home
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-housing}
      MODEL_PATH: /app/models/model.joblib
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
    volumes:
      - ./src:/app/src:cached
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml:cached
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml:cached
      - dagster_home:/opt/dagster/dagster_home
      - ./models:/app/models:cached
    restart: unless-stopped
    networks:
      - housing-network

  dagster-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run dagster-webserver -h 0.0.0.0 -p 3000 -w /opt/dagster/dagster_home/workspace.yaml
    ports:
      - "3000:3000"
    environment:
      PYTHONPATH: /app
      DAGSTER_HOME: /opt/dagster/dagster_home
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-housing}
      MODEL_PATH: /app/models/model.joblib
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
    volumes:
      - ./src:/app/src:cached
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml:cached
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml:cached
      - dagster_home:/opt/dagster/dagster_home
      - ./models:/app/models:cached
    depends_on:
      dagster-daemon:
        condition: service_started
    networks:
      - housing-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn "src.adapter.driving.fastapi.app:app" --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-housing}
      MODEL_PATH: /app/models/model.joblib
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8000}
      DAGSTER_WEBSERVER_URL: http://dagster-webserver:3000
    volumes:
      - ./src:/app/src:cached
      - ./models:/app/models:cached
    depends_on:
      postgres:
        condition: service_healthy
      dagster-webserver:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - housing-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - housing-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - housing-network

networks:
  housing-network:
    driver: bridge

volumes:
  postgres_data:
  dagster_home:
  grafana_data:
